# Generated by Django 2.1.15 on 2023-04-15 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipies', '0003_auto_20230414_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ratings',
            field=models.ManyToManyField(related_name='rated_recipes', through='recipies.RecipeRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.Recipe'),
        ),
    ]
