# Generated by Django 2.1.15 on 2023-04-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_auto_20230415_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recipies.Recipe'),
        ),
    ]
